name: church
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  styled_widget: ^0.4.0+3
  camera: 0.10.3+2
  http: 0.13.5
  flutter:
    sdk: flutter
  alan_voice: ^3.12.0
  zego_uikit_prebuilt_live_audio_room: ^2.2.2
  persistent_bottom_nav_bar: ^5.0.2
  youtube_player_flutter: ^8.1.2
  flutter_svg: ^2.0.4

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

  csv: ^5.0.1

flutter_icons:
  image_path_android: "assets/icons/ic_appicon.png"
  image_path_ios: "assets/icons/ic_appicon_ios.jpg"
  android: true
  ios: true
  adaptive_icon_foreground: "assets/icons/ic_appicon_foreground.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true

  generate: false

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/json/alkitab.json

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic

